# Solution
***

## a)

In [1]:
#Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf

In [2]:
#Creating data
x = np.array([1, 2, 3, 4, 5])
y = np.array([0.83, 6.99, 7.57, 5.99, 9.84])
n = x.size

In [3]:
#Calculating a1
frac1 = n * (x * y).sum() - y.sum() * x.sum()
frac2 = n * (x**2).sum() - x.sum()**2
a1 = frac1 / frac2

In [4]:
#Calculating a0
a0 = y.mean() - a1 * x.mean()

In [5]:
#Function
f = a0 + a1 * x
print(f)

[2.84  4.542 6.244 7.946 9.648]


## b)

In [6]:
df = pd.DataFrame({'x' : x, 'y' : y})
model1 = smf.ols('y ~ x', data = df)
m1 = model1.fit()
print(m1.params)

df_new = pd.DataFrame({'x' : [3], 'y' : [0]})
pred1 = m1.predict(df_new)
print(f'{pred1[0]:.3f}')

Intercept    1.138
x            1.702
dtype: float64
6.244


## c)

In [7]:
#Prediction for different K
x0 = 3
distances = np.abs(x - x0)
print(distances)

[2 1 0 1 2]


In [8]:
#Sort distances by index
sorted_idx = np.argsort(distances)
print(sorted_idx)

[2 1 3 0 4]


In [9]:
#K = 1
k1 = np.mean(y[sorted_idx[:1]])
print(k1)

7.57


In [10]:
#K = 3
k3 = np.mean(y[sorted_idx[:3]])
print(round(k3, 2))

6.85


In [11]:
#K = 5
k5 = np.mean(y[sorted_idx[:5]])
print(round(k5, 2))

6.24


In [12]:
#Print results
print(f'Predicted value for K = 1 is {k1:.2f}')
print(f'Predicted value for K = 3 is {k3:.2f}')
print(f'Predicted value for K = 5 is {k5:.2f}')

Predicted value for K = 1 is 7.57
Predicted value for K = 3 is 6.85
Predicted value for K = 5 is 6.24


## d)

In [13]:
#Function for KNN
def knn(x0, x, y, K = 20):
    d = np.abs(x - x0)
    o = np.argsort(d)[:K]
    ypred = np.mean(y[o])
    return ypred

In [14]:
#Experimenting with the function
K = 3
x0 = 3
d = np.abs(x - x0)
o = np.argsort(d)[:K]
ypred = np.mean(y[o])
print(round(ypred, 2))

6.85


# Task 2
***

## a)
***

In [18]:
#Loading data
from ISLP import load_data

College = load_data('College')
College.describe(include = 'all')

,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
count,777,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.00000
unique,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,565,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,3001.638353,2018.804376,779.972973,27.558559,55.796654,3699.907336,855.298584,10440.669241,4357.526384,549.380952,1340.642214,72.660232,79.702703,14.089704,22.743887,9660.171171,65.46332
std,NaN,3870.201484,2451.113971,929.176190,17.640364,19.804778,4850.420531,1522.431887,4023.016484,1096.696416,165.105360,677.071454,16.328155,14.722359,3.958349,12.391801,5221.768440,17.17771
min,NaN,81.000000,72.000000,35.000000,1.000000,9.000000,139.000000,1.000000,2340.000000,1780.000000,96.000000,250.000000,8.000000,24.000000,2.500000,0.000000,3186.000000,10.00000
25%,NaN,776.000000,604.000000,242.000000,15.000000,41.000000,992.000000,95.000000,7320.000000,3597.000000,470.000000,850.000000,62.000000,71.000000,11.500000,13.000000,6751.000000,53.00000
50%,NaN,1558.000000,1110.000000,434.000000,23.000000,54.000000,1707.000000,353.000000,9990.000000,4200.000000,500.000000,1200.000000,75.000000,82.000000,13.600000,21.000000,8377.000000,65.00000
75%,NaN,3624.000000,2424.000000,902.000000,35.000000,69.000000,4005.000000,967.000000,12925.000000,5050.000000,600.000000,1700.000000,85.000000,92.000000,16.500000,31.000000,10830.000000,78.00000


## b)
***

In [ ]:
#Dividing data 50/50 into trainind and test sets
np.random.seed(123)
n = College.shape[0]
train_idx = np.random.choice(n, size = n // 2, replace = False)
train = College.iloc[train_idx]
test = College.drop(College.index[train_idx])