# Solution
***

## a)

In [1]:
#Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf

In [2]:
#Creating data
x = np.array([1, 2, 3, 4, 5])
y = np.array([0.83, 6.99, 7.57, 5.99, 9.84])
n = x.size

In [3]:
#Calculating a1
frac1 = n * (x * y).sum() - y.sum() * x.sum()
frac2 = n * (x**2).sum() - x.sum()**2
a1 = frac1 / frac2

In [4]:
#Calculating a0
a0 = y.mean() - a1 * x.mean()

In [5]:
#Function
f = a0 + a1 * x
print(f)

[2.84  4.542 6.244 7.946 9.648]


## b)

In [6]:
df = pd.DataFrame({'x' : x, 'y' : y})
model1 = smf.ols('y ~ x', data = df)
m1 = model1.fit()
print(m1.params)

df_new = pd.DataFrame({'x' : [3], 'y' : [0]})
pred1 = m1.predict(df_new)
print(f'{pred1[0]:.3f}')

Intercept    1.138
x            1.702
dtype: float64
6.244


## c)

In [7]:
#Prediction for diffrent K
x0 = 3
distances = np.abs(x - x0)
print(distances)

[2 1 0 1 2]


In [8]:
#Sort distances by index
sorted_idx = np.argsort(distances)
print(sorted_idx)

[2 1 3 0 4]


In [9]:
#K = 1
k1 = np.mean(y[sorted_idx[:1]])
print(k1)

7.57


In [10]:
#K = 3
k3 = np.mean(y[sorted_idx[:3]])
print(round(k3, 2))

6.85


In [11]:
#K = 5
k5 = np.mean(y[sorted_idx[:5]])
print(round(k5, 2))

6.24


In [12]:
#Print results
print(f'Predicted value for K = 1 is {k1:.2f}')
print(f'Predicted value for K = 3 is {k3:.2f}')
print(f'Predicted value for K = 5 is {k5:.2f}')

Predicted value for K = 1 is 7.57
Predicted value for K = 3 is 6.85
Predicted value for K = 5 is 6.24


## d)

In [ ]:
#Function for KNN
def knn(x0, x, y, K = 20):
    d = np.abs(x - x0)
    o = np.argsort(d)[:K]
    ypred = np.mean(y[o])
    return ypred

In [25]:
#Experimenting with the function
K = 3
x0 = 3
d = np.abs(x - x0)
o = np.argsort(d)[:K]
ypred = np.mean(y[o])
print(round(ypred, 2))

6.85


## e)

In [ ]:
#